const PERMISSIONS = {
  CONSULT: {
    $name: 'CONSULT',
    $route: 'activities',
    DELETE: 'delete:consult',
    PUT: 'put:consult',
    POST: 'post:consult',
    GET: 'get:consult',
  },
  CONSULT_AWAITING: {
    $name: 'CONSULT_AWAITING',
    $route: 'activities-awaiting',
    DELETE: 'delete:consult-awaiting',
    PUT: 'put:consult-awaiting',
    POST: 'post:consult-awaiting',
    GET: 'get:consult-awaiting',
  },
  RESPONSE_SHEET: {
    $name: 'RESPONSE_SHEET',
    $route: 'answer',
    DELETE: 'delete:response-sheet',
    PUT: 'put:response-sheet',
    POST: 'post:response-sheet',
    GET: 'get:response-sheet',
  },
  HISTORIC_RESPONSE_SHEET: {
    $name: 'HISTORIC_RESPONSE_SHEET',
    $route: 'answer',
    DELETE: 'delete:historic-response-sheet',
    PUT: 'put:historic-response-sheet',
    POST: 'post:historic-response-sheet',
    GET: 'get:historic-response-sheet',
  },
  PATIENTS: {
    $name: 'PATIENTS',
    $route: 'clients',
    DELETE: 'delete:patients',
    PUT: 'put:patients',
    POST: 'post:patients',
    GET: 'get:patients',
  },
  PROFESSIONALS: {
    $name: 'PROFESSIONALS',
    $route: 'professionals',
    DELETE: 'delete:professionals',
    PUT: 'put:professionals',
    POST: 'post:professionals',
    GET: 'get:professionals',
  },
  SECRETARIES: {
    $name: 'SECRETARIES',
    $route: 'secs',
    DELETE: 'delete:secretaries',
    PUT: 'put:secretaries',
    POST: 'post:secretaries',
    GET: 'get:secretaries',
  },
  PARTNERS: {
    $name: 'PARTNERS',
    $route: 'partner',
    DELETE: 'delete:partners',
    PUT: 'put:partners',
    POST: 'post:partners',
    GET: 'get:partners',
  },
  PROCEDURES: {
    $name: 'PROCEDURES',
    $route: 'procedure',
    DELETE: 'delete:procedures',
    PUT: 'put:procedures',
    POST: 'post:procedures',
    GET: 'get:procedures',
  },
  CATEGORIES: {
    $name: 'CATEGORIES',
    $route: 'category',
    DELETE: 'delete:categories',
    PUT: 'put:categories',
    POST: 'post:categories',
    GET: 'get:categories',
  },
  CHARTS: {
    $name: 'CHARTS',
    $route: 'form',
    DELETE: 'delete:charts',
    PUT: 'put:charts',
    POST: 'post:charts',
    GET: 'get:charts',
  },
  HISTORIC_CHARTS: {
    $name: 'HISTORIC_CHARTS',
    $route: 'form',
    DELETE: 'delete:historic-charts',
    PUT: 'put:historic-charts',
    POST: 'post:historic-charts',
    GET: 'get:historic-charts',
  },
  HEALTH_INSURANCES: {
    $name: 'HEALTH_INSURANCES',
    $route: 'health-insurances',
    DELETE: 'delete:health-insurances',
    PUT: 'put:health-insurances',
    POST: 'post:health-insurances',
    GET: 'get:health-insurances',
  }
};

module.exports = PERMISSIONS;
