import { model, Schema } from '@ioc:Mongoose';
import { IPermission } from 'Types/IPermission';

const PermissionSchema = new Schema<IPermission>(
    {
        
        admin_activity: { type: Boolean, required: true },
        admin_prof_activity: { type: Boolean, required: true },
        prof_activity: { type: Boolean, required: true },
        sec_activity: { type: Boolean, required: true },
        admin_activity_await: { type: Boolean, required: true },
        admin_prof_activity_await: { type: Boolean, required: true },
        prof_activity_await: { type: Boolean, required: true },
        sec_activity_await: { type: Boolean, required: true },
        admin_answers: { type: Boolean, required: true },
        admin_prof_answers: { type: Boolean, required: true },
        prof_answers: { type: Boolean, required: true },
        sec_answers: { type: Boolean, required: true },
        admin_answers_historic: { type: Boolean, required: true },
        admin_prof_answers_historic: { type: Boolean, required: true },
        prof_answers_historic: { type: Boolean, required: true },
        sec_answers_historic: { type: Boolean, required: true },
        admin_clients: { type: Boolean, required: true },
        admin_prof_clients: { type: Boolean, required: true },
        prof_clients: { type: Boolean, required: true },
        sec_clients: { type: Boolean, required: true },
        admin_company: { type: Boolean, required: true },
        admin_prof_company: { type: Boolean, required: true },
        prof_company: { type: Boolean, required: true },
        sec_company: { type: Boolean, required: true },
        admin_form: { type: Boolean, required: true },
        admin_prof_form: { type: Boolean, required: true },
        prof_form: { type: Boolean, required: true },
        sec_form: { type: Boolean, required: true },
        admin_form_historic: { type: Boolean, required: true },
        admin_prof_form_historic: { type: Boolean, required: true },
        prof_form_historic: { type: Boolean, required: true },
        sec_form_historic: { type: Boolean, required: true },
        admin_clients_list: { type: Boolean, required: true },
        admin_prof_clients_list: { type: Boolean, required: true },
        prof_clients_list: { type: Boolean, required: true },
        sec_clients_list: { type: Boolean, required: true },
        admin_prof_list: { type: Boolean, required: true },
        admin_prof_prof_list: { type: Boolean, required: true },
        prof_prof_list: { type: Boolean, required: true },
        sec_prof_list: { type: Boolean, required: true },
        admin_sec_list: { type: Boolean, required: true },
        admin_prof_sec_list: { type: Boolean, required: true },
        prof_sec_list: { type: Boolean, required: true },
        sec_sec_list: { type: Boolean, required: true },
        admin_my_activities: { type: Boolean, required: true },
        admin_prof_my_activities: { type: Boolean, required: true },
        prof_my_activities: { type: Boolean, required: true },
        sec_my_activities: { type: Boolean, required: true },
        admin_partner: { type: Boolean, required: true },
        admin_prof_partner: { type: Boolean, required: true },
        prof_partner:  { type: Boolean, required: true },
        sec_partner: { type: Boolean, required: true },
        admin_partner_create: { type: Boolean, required: true },
        admin_prof_partner_create: { type: Boolean, required: true },
        prof_partner_create: { type: Boolean, required: true },
        sec_partner_create: { type: Boolean, required: true },
        admin_permissions: { type: Boolean, required: true },
        admin_prof_permissions: { type: Boolean, required: true },
        prof_permissions: { type: Boolean, required: true },
        sec_permissions: { type: Boolean, required: true },
        admin_procedures: { type: Boolean, required: true },
        admin_prof_procedures: { type: Boolean, required: true },
        prof_procedures: { type: Boolean, required: true },
        sec_procedures: { type: Boolean, required: true },
        admin_procedures_create: { type: Boolean, required: true },
        admin_prof_procedures_create: { type: Boolean, required: true },
        prof_procedures_create: { type: Boolean, required: true },
        sec_procedures_create: { type: Boolean, required: true },
        admin_schedule: { type: Boolean, required: true },
        admin_prof_schedule: { type: Boolean, required: true },
        prof_schedule: { type: Boolean, required: true },
        sec_schedule: { type: Boolean, required: true },
        admin_category: { type: Boolean, required: true },
        admin_prof_category: { type: Boolean, required: true },
        prof_category: { type: Boolean, required: true },
        sec_category: { type: Boolean, required: true },
        unity_id: { type: Schema.Types.ObjectId, required: true },

    },
    { timestamps: true }
);

export default model<IPermission>('permissions', PermissionSchema);