import Mongoose, { Schema } from '@ioc:Mongoose'
import { IPhone, IUnity } from 'Types/IUnity'
// Generated by https://quicktype.io

export const UnitySchema = new Schema<IUnity>(
	{
		name: {
			type: String,
			required: true,
		},
		active: {
			type: Boolean,
			required: true,
		},
		address: {
			type: String,
			required: false,
		},
		address_number: {
			type: String,
			required: false,
		},
		avatar: {
			type: String,
			required: false,
		},
		city: {
			type: String,
			required: false,
		},
		cep: {
			type: String,
			required: false,
		},
		cnaes: {
			type: Array,
			required: false,
		},
		complement: {
			type: String,
			required: false,
		},
		country: {
			type: String,
			required: false,
		},
		date_expiration: {
			type: Date,
			required: true,
		},
		document: {
			type: String,
			required: true,
		},
		email: {
			type: String,
			required: true,
		},
		is_company: {
			type: Boolean,
			required: true,
		},
		name_company: {
			type: String,
			required: false,
		},
		neighbohood: {
			type: String,
			required: false,
		},
		obs: {
			type: String,
			required: false,
		},
		phones: new Mongoose.SchemaTypeOptions<IPhone[]>(),
		site: {
			type: String,
			required: false,
		},
		state: {
			type: String,
			required: false,
		},
	},
	{
		timestamps: {
			createdAt: 'created_at',
			updatedAt: 'updated_at',
		},
	},
)

export default Mongoose.model<IUnity>('unities', UnitySchema)
