import Mongoose, { Schema } from '@ioc:Mongoose'
import { IPhone, IUnity } from 'Types/IUnity'
// Generated by https://quicktype.io

/**
 * @swagger
 * components:
 *   schemas:
 *     Unity:
 *       type: object
 *       properties:
 *         name:
 *           type: string
 *           description: The name of the unity.
 *           required: true
 *         active:
 *           type: boolean
 *           description: The active status of the unity.
 *           required: true
 *         address:
 *           type: string
 *           description: The address of the unity.
 *         address_number:
 *           type: string
 *           description: The address number of the unity.
 *         avatar:
 *           type: string
 *           description: The avatar URL of the unity.
 *         city:
 *           type: string
 *           description: The city where the unity is located.
 *         cep:
 *           type: string
 *           description: The postal code of the unity.
 *         cnaes:
 *           type: array
 *           description: The list of CNAEs associated with the unity.
 *           items:
 *             type: string
 *         complement:
 *           type: string
 *           description: Additional information related to the unity's address.
 *         country:
 *           type: string
 *           description: The country where the unity is located.
 *         date_expiration:
 *           type: string
 *           format: date
 *           description: The expiration date of the unity.
 *           required: true
 *         document:
 *           type: string
 *           description: The unity's document identifier.
 *           required: true
 *         email:
 *           type: string
 *           description: The email address associated with the unity.
 *           required: true
 *         is_company:
 *           type: boolean
 *           description: Indicates whether the unity is a company or not.
 *           required: true
 *         name_company:
 *           type: string
 *           description: The name of the company, if the unity is a company.
 *         neighbohood:
 *           type: string
 *           description: The neighborhood where the unity is located.
 *         obs:
 *           type: string
 *           description: Observations about the unity.
 *         phones:
 *           type: array
 *           description: A list of phone numbers associated with the unity.
 *           items:
 *             $ref: '#/components/schemas/Phone'
 *         site:
 *           type: string
 *           description: The website URL of the unity.
 *         state:
 *           type: string
 *           description: The state where the unity is located.
 *         created_at:
 *           type: string
 *           format: date-time
 *           description: The date and time when the unity was created.
 *           readOnly: true
 *         updated_at:
 *           type: string
 *           format: date-time
 *           description: The date and time when the unity was last updated.
 *           readOnly: true
 *     Phone:
 *       type: object
 *       properties:
 *         # Add properties for the IPhone schema
 */
export const UnitySchema = new Schema<IUnity>({
	name: {
		type: String,
		required: true,
	},
	active: {
		type: Boolean,
		required: true,
	},
	address: {
		type: String,
		required: false,
	},
	address_number: {
		type: String,
		required: false,
	},
	avatar: {
		type: String,
		required: false,
	},
	city: {
		type: String,
		required: false,
	},
	cep: {
		type: String,
		required: false,
	},
	cnaes: {
		type: Array,
		required: false,
	},
	complement: {
		type: String,
		required: false,
	},
	country: {
		type: String,
		required: false,
	},
	date_expiration: {
		type: Date,
		required: true,
	},
	document: {
		type: String,
		required: true,
	},
	email: {
		type: String,
		required: true,
	},
	is_company: {
		type: Boolean,
		required: true,
	},
	name_company: {
		type: String,
		required: false,
	},
	neighbohood: {
		type: String,
		required: false,
	},
	obs: {
		type: String,
		required: false,
	},
	phones: new Mongoose.SchemaTypeOptions<IPhone[]>(),
	site: {
		type: String,
		required: false,
	},
	state: {
		type: String,
		required: false,
	},
	created_at: {
		type: Date,
		default: Date.now,
	},
	updated_at: {
		type: Date,
		default: Date.now,
	},
})

export default Mongoose.model<IUnity>('unities', UnitySchema)
