export enum CACHE_REPORTS {
	GENDER = 'census_gender',
	NEW_OLD_CLIENTS = 'census_new_old_clients',
	PARTNERS = 'census_partners',
	ACTIVITIES_BY_DAYS_OF_WEEK = 'census_activities_by_days_of_week',
	ACTIVITIES_BY_MONTHS = 'census_activities_by_months',
	ACTIVITIES_OF_SCHEDULED = 'census_activities_of_scheduled',
	HOURS_WORKED = 'census_hours_worked',
	PROCEDURES = 'census_procedures',
	HEALTH_INSURANCES = 'census_health_insurances',
	MEDIA_TIME_ATTENDANCE = 'census_media_time_attendance',
	ACTIVITIES_OF_PROF = 'census_activities_of_prof',
	PAYMENTS_PARTICIPATIONS = 'census_payments_participations',
	PAYMENTS_FORMS = 'census_payments_forms',
	PAYMENTS_BY_PARTNERS = 'census_payments_by_partners',
	PAYMENTS_BY_PROF = 'census_payments_by_prof',
	PAYMENTS_BY_HEALTH_INSURANCE = 'census_payments_by_health_insurance',
	REVENUES_ACCRUAL_REGIME = 'census_revenues_accrual_regime',
	REVENUES_CASH_REGIME = 'census_revenues_cash_regime',
	COST = 'census_cost',
}
