/* eslint-disable @typescript-eslint/naming-convention */
// Generated by https://quicktype.io
import { ObjectId } from '@ioc:Mongoose'

import { IAddress } from './IAddress'
import { IFormAnswer } from './IFormAnswer'

export interface IUserClient extends Partial<IAddress> {
	_id?: string
	name: string
	avatar?: string
	form_answers: IFormAnswer[]
	birth_date: string | Date
	gender?: 'male' | 'female' | 'other' | 'not informed'
	document: string
	rg?: string
	celphone: string
	phone?: string
	naturalness?: string
	nationality?: string
	profession?: string
	observation?: string
	sms_checked?: boolean
	mail_checked?: boolean
	email: string
	unity_id: ObjectId | string
	active?: boolean
	partner?: {
		value: string
		label: string
	}
	due_date?: Date
	created_at?: Date
	updated_at?: Date
}

export interface IClient {
	value: string
	label: string
	celphone?: string
	email?: string
	partner?: {
		value: string
		label: string
	}
}
