/* eslint-disable @typescript-eslint/naming-convention */
// Generated by https://quicktype.io
import { ObjectId } from '@ioc:Mongoose'
import { ROLES } from 'App/Roles/types'
import { Genders } from './IClient'
import type { IDaysOffice } from './IDaysOffice'
import { Generic } from './ITransaction'

export interface IUser extends Omit<IDaysOffice, 'unity_id'> {
	_id: string
	name: string
	email: string
	gender?: Genders | Generic
	password: string
	celphone: string
	document: string
	unity_id: ObjectId | string
	type: ROLES
	active: boolean
	avatar: string
	due_date: string
	created_at: Date
	updated_at: Date
	schedule_obs: string
	show_lack: boolean
	specialty: string
	board: string
	record: string
	profession: string
	occupation_code: string
	rememberMeToken?: string
	performs_medical_appointments?: boolean
	permissions?: string[]
	blacklist?: string[]
}

export interface IProfile {
	_id: string | ObjectId
	name: string
	active: boolean
	avatar: string
	email?: string
	phone: string
	celphone: string
	document?: string
	unity_id: ObjectId | string
	performs_medical_appointments?: boolean
	gender?: Genders | Generic
	specialty: string
	board: string
	record: string
	profession: string
	occupation_code: string
	show_lack: boolean
	type?: ROLES
}